pipeline { 

    agent any 
    
	tools {
		maven  "Maven"
		}
		
    stages {
			
        stage("build") {
            steps {
                echo "Building an application using maven"
				sh 'mvn -f /var/lib/jenkins/workspace/GlidedRose/Java/pom.xml package'
				}
			post {
				success{
					echo "Artificat is generated succesfully"
					echo "Archiving an artifact"
					archiveArtifacts artifacts: '**/*.war', followSymlinks: false
					}
				failure{
					echo "Failed to generate an artifact"
					}
				}
			}
		
		
			stage ("Deploy to Staging"){
				steps{
					deploy adapters: [tomcat8(credentialsId: '1ee3f9cc-2675-448f-b19b-7268da7b2fcb', path: '', url: 'http:\\\\ec2-3-12-111-24.us-east-2.compute.amazonaws.com:8888')], contextPath: null, onFailure: false, war: '**/*.war'
					}
				post {
					success {
						echo "Application is deployed sucecsfully on Tomcat in staging env"
							}
					failure {
						echo " Filed to deploy app. on tomcat server"
							}
					}
				}
	
		}
	
	}